module LibRawWrapper

using CEnum
include("raw.jl")
using .LibRawRaw

for name in names(LibRawRaw; all = true)
    startswith(String(name), "libraw_") || continue
    @eval const $name = LibRawRaw.$name
    @eval export $name
end

include("types.jl")
include("highlevel.jl")
include("snapshots.jl")
include("sensor.jl")
include("processing.jl")
export LibRawProcessor,
    LibRawError,
    open!,
    unpack!,
    unpack_thumbnail!,
    process!,
    recycle!,
    close!,
    processed_image,
    thumbnail,
    rgb_cam_matrix,
    metadata,
    ImageSizes,
    ImageIdentity,
    ColorData,
    ImageOther,
    LensInfo,
    ShootingInfo,
    ThumbnailInfo,
    RawDataInfo,
    RawSnapshot,
    snapshot,
    image_sizes,
    image_identity,
    color_data,
    image_other,
    lens_info,
    shooting_info,
    thumbnail_info,
    raw_data_info
export openraw,
    isfatal,
    ProcessorState,
    Empty,
    Opened,
    Unpacked,
    Working,
    Processed,
    Failed,
    Closed,
    ProcessingParams,
    WhiteBalance,
    DaylightWB,
    CameraWB,
    AutoWB,
    CustomWB,
    ColorSpace,
    CameraColor,
    SRGB,
    AdobeRGB,
    WideGamutRGB,
    ProPhotoRGB,
    XYZ,
    ACES,
    DemosaicAlgorithm,
    DefaultDemosaic,
    LinearDemosaic,
    VNG,
    PPG,
    AHD,
    DCB,
    DHT,
    AAHD,
    Orientation,
    CameraOrientation,
    Unrotated,
    Rotate180,
    Rotate90CCW,
    Rotate90CW,
    HighlightMode,
    ClipHighlights,
    PreserveHighlights,
    BlendHighlights,
    ReconstructHighlights,
    SensorLayout,
    CFALayout,
    MonochromeLayout,
    MultichannelLayout,
    SensorImage,
    CFAKind,
    Bayer,
    XTrans,
    PeriodicCFA,
    sensor_image,
    cfa_pattern,
    color_index,
    color_indices,
    prepare_image!,
    working_image,
    postprocess!,
    ProcessedImage,
    OutputMetadata,
    AbstractThumbnail,
    JPEGThumbnail,
    BitmapThumbnail,
    extract_thumbnail!,
    ProcessingWarnings,
    warnings,
    tone_curve
end
